; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduboy]
platform = atmelavr
board = arduboy
framework = arduino
upload_port = COM7
lib_deps =
	mlxxxp/Arduboy2@^6.0.0
	https://github.com/MrBlinky/ArduboyFX.git
monitor_speed = 9600
extra_scripts = post:scripts/platformio_fx.py
custom_fx_upload_on_upload = yes
custom_fx_port = COM7
custom_fx_upload_only_if_changed = yes
