#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xffff;
constexpr uint24_t FX_DATA_BYTES = 7;

constexpr uint24_t FX_GAME_TITLE = 0x000000;
