name: Build Arduboy HEX

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PlatformIO
        run: |
          python3 -m pip install --upgrade pip
          pip install platformio

      - name: Build
        run: |
          pio run
      
          # Get last commit message (before this workflow commit)
          LAST_COMMIT=$(git log -2 --pretty=%B | tail -n 1)

          # Sanitize for filenames
          SAFE_LAST_COMMIT="${LAST_COMMIT// /-}"
          SAFE_LAST_COMMIT="${SAFE_LAST_COMMIT//\//-}"
      
      - name: Export HEX
        run: |
          mkdir -p docs
          cp .pio/build/arduboy/firmware.hex docs/qixboy.hex

      - name: Commit HEX
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add "docs/qixboy.hex"
          git commit -m "${SAFE_LAST_COMMIT}-(hex-archive).hex" || echo "No changes"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:"${{ github.ref_name }}"